# Generated by Django 3.2.7 on 2021-10-14 13:04

from django.db import migrations, models
import languages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('short_name', models.CharField(max_length=25, verbose_name='Краткое_название')),
                ('icon', models.ImageField(max_length=255, upload_to=languages.models.lang_icon_path, verbose_name='Иконка')),
            ],
        ),
    ]
