# Generated by Django 3.2.7 on 2022-02-10 17:08

from django.db import migrations, models
import languages.models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='short_name',
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=languages.models.lang_icon_path, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Название'),
        ),
    ]
