# Generated by Django 3.2.7 on 2022-03-11 11:49

from django.db import migrations, models
import languages.models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20220210_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=languages.models.lang_icon_path, verbose_name='Иконка'),
        ),
    ]
