# Generated by Django 3.2.7 on 2022-03-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_alter_language_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='icon',
            new_name='image',
        ),
    ]
