# Generated by Django 3.2.7 on 2022-04-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoplaces', '0024_auto_20220407_2127'),
        ('accounts', '0026_user_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_operator_license', models.BooleanField(default=False)),
                ('had_commercial_tours', models.BooleanField(default=False)),
                ('aproved', models.BooleanField(default=False)),
                ('recipient_inn', models.CharField(max_length=255, verbose_name='ИНН Получателя')),
                ('recipient_ogrn', models.CharField(max_length=255, verbose_name='ОГРН Получателя')),
                ('recipient_legal_address', models.CharField(max_length=255, verbose_name='Юр адрес')),
                ('recipient_real_address', models.CharField(max_length=255, verbose_name='Фактический адрес')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geoplaces.country', verbose_name='Резидент')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.expert', verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Запрос на проверку юр лицо',
                'verbose_name_plural': 'Запросы на проверку юр лицо',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_operator_license', models.BooleanField(default=False)),
                ('had_commercial_tours', models.BooleanField(default=False)),
                ('aproved', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('passport_series', models.PositiveIntegerField(verbose_name='Паспорт серия')),
                ('passport_number', models.PositiveIntegerField(verbose_name='Паспорт номер')),
                ('passport_code_issued_by', models.CharField(max_length=25, verbose_name='Паспорт код подразделения')),
                ('passport_issued_by', models.CharField(max_length=255, verbose_name='Паспорт кем выдан')),
                ('passport_date', models.DateField(verbose_name='Паспорт дата выдачи')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geoplaces.country', verbose_name='Резидент')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.expert', verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Запрос на проверку физ лицо',
                'verbose_name_plural': 'Запросы на проверку физ лицо',
            },
        ),
    ]
