# Generated by Django 3.2.7 on 2022-04-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0024_auto_20220407_2127'),
        ('verificationrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='about_conflict',
            field=models.TextField(blank=True, null=True, verbose_name='Описание конфликта'),
        ),
        migrations.AddField(
            model_name='individual',
            name='countries',
            field=models.ManyToManyField(to='geoplaces.Country', verbose_name='В какие страны туры'),
        ),
        migrations.AddField(
            model_name='individual',
            name='had_conflicts',
            field=models.BooleanField(default=False, verbose_name='Были конфликты?'),
        ),
        migrations.AddField(
            model_name='individual',
            name='number_tours_per_year',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'до 5'), (2, '5-12'), (3, '13-20'), (4, '21-30'), (5, '30+')], null=True, verbose_name='Туры в год'),
        ),
        migrations.AddField(
            model_name='individual',
            name='other_sites',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылки на ресурсы'),
        ),
        migrations.AddField(
            model_name='legal',
            name='about_conflict',
            field=models.TextField(blank=True, null=True, verbose_name='Описание конфликта'),
        ),
        migrations.AddField(
            model_name='legal',
            name='countries',
            field=models.ManyToManyField(to='geoplaces.Country', verbose_name='В какие страны туры'),
        ),
        migrations.AddField(
            model_name='legal',
            name='had_conflicts',
            field=models.BooleanField(default=False, verbose_name='Были конфликты?'),
        ),
        migrations.AddField(
            model_name='legal',
            name='number_tours_per_year',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'до 5'), (2, '5-12'), (3, '13-20'), (4, '21-30'), (5, '30+')], null=True, verbose_name='Туры в год'),
        ),
        migrations.AddField(
            model_name='legal',
            name='other_sites',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылки на ресурсы'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificationrequests_individual_citizenship', to='geoplaces.country', verbose_name='Резидент'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificationrequests_legal_citizenship', to='geoplaces.country', verbose_name='Резидент'),
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='scans')),
                ('legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='verificationrequests.legal', verbose_name='Запрос на проверку юр лица')),
            ],
        ),
    ]
