# Generated by Django 3.2.7 on 2022-04-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_patronymic'),
        ('verificationrequests', '0002_auto_20220427_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='had_commercial_tours',
            new_name='commercial_tours',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='had_conflicts',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='about_conflict',
            new_name='conflicts_review',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='tour_operator_license',
            new_name='license',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='citizenship',
            new_name='residency',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='countries',
            new_name='tours_countries',
        ),
        migrations.RenameField(
            model_name='legal',
            old_name='had_commercial_tours',
            new_name='commercial_tours',
        ),
        migrations.RenameField(
            model_name='legal',
            old_name='had_conflicts',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='legal',
            old_name='about_conflict',
            new_name='conflicts_review',
        ),
        migrations.RenameField(
            model_name='legal',
            old_name='tour_operator_license',
            new_name='license',
        ),
        migrations.RenameField(
            model_name='legal',
            old_name='citizenship',
            new_name='residency',
        ),
        migrations.RenameField(
            model_name='legal',
            old_name='countries',
            new_name='tours_countries',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='number_tours_per_year',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='other_sites',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='number_tours_per_year',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='other_sites',
        ),
        migrations.AddField(
            model_name='individual',
            name='commercial_tours_yearly',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Туры в год'),
        ),
        migrations.AddField(
            model_name='individual',
            name='legal_restrictions',
            field=models.BooleanField(default=False, verbose_name='Были конфликты?'),
        ),
        migrations.AddField(
            model_name='individual',
            name='legal_restrictions_review',
            field=models.TextField(blank=True, null=True, verbose_name='Описание конфликта'),
        ),
        migrations.AddField(
            model_name='individual',
            name='reviews_links',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылки на отзывы'),
        ),
        migrations.AddField(
            model_name='individual',
            name='tours_links',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылки на туры'),
        ),
        migrations.AddField(
            model_name='legal',
            name='commercial_tours_yearly',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Туры в год'),
        ),
        migrations.AddField(
            model_name='legal',
            name='legal_restrictions',
            field=models.BooleanField(default=False, verbose_name='Были конфликты?'),
        ),
        migrations.AddField(
            model_name='legal',
            name='legal_restrictions_review',
            field=models.TextField(blank=True, null=True, verbose_name='Описание конфликта'),
        ),
        migrations.AddField(
            model_name='legal',
            name='reviews_links',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылки на отзывы'),
        ),
        migrations.AddField(
            model_name='legal',
            name='tours_links',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылки на туры'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='expert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='individual_verification', to='accounts.expert', verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='expert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='legal_verification', to='accounts.expert', verbose_name='Эксперт'),
        ),
    ]
