# Generated by Django 3.2.7 on 2022-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificationrequests', '0003_auto_20220429_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='commercial_tours',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Коммерческие туры'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='legal_restrictions',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Были конфликты?'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='license',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Наличие лицензии'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='commercial_tours',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Коммерческие туры'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='legal_restrictions',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Были конфликты?'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='license',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Наличие лицензии'),
        ),
    ]
