# Generated by Django 3.2.7 on 2022-04-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0024_auto_20220407_2127'),
        ('verificationrequests', '0004_auto_20220429_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='residency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificationrequests_individual_citizenship', to='geoplaces.country', verbose_name='Резидент'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='tours_countries',
            field=models.ManyToManyField(blank=True, null=True, to='geoplaces.Country', verbose_name='В какие страны туры'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='residency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificationrequests_legal_citizenship', to='geoplaces.country', verbose_name='Резидент'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='tours_countries',
            field=models.ManyToManyField(blank=True, null=True, to='geoplaces.Country', verbose_name='В какие страны туры'),
        ),
    ]
