# Generated by Django 3.2.7 on 2022-04-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificationrequests', '0005_auto_20220429_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='passport_number',
            field=models.CharField(max_length=255, verbose_name='Паспорт номер'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='passport_series',
            field=models.CharField(max_length=255, verbose_name='Паспорт серия'),
        ),
    ]
