# Generated by Django 3.2.7 on 2022-04-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificationrequests', '0006_auto_20220429_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='conflicts',
            field=models.TextField(default='No', max_length=6, verbose_name='Были конфликты?'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='conflicts',
            field=models.TextField(default='No', max_length=6, verbose_name='Были конфликты?'),
        ),
    ]
