# Generated by Django 3.2.7 on 2022-04-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_patronymic'),
        ('verificationrequests', '0007_auto_20220429_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'verbose_name': 'Скан документа', 'verbose_name_plural': 'Сканы документов'},
        ),
        migrations.RemoveField(
            model_name='scan',
            name='legal',
        ),
        migrations.AddField(
            model_name='scan',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='accounts.expert', verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='conflicts',
            field=models.TextField(default='no', max_length=6, verbose_name='Были конфликты?'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='legal_restrictions',
            field=models.CharField(default='no', max_length=6, verbose_name='Были конфликты?'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='conflicts',
            field=models.TextField(default='no', max_length=6, verbose_name='Были конфликты?'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='legal_restrictions',
            field=models.CharField(default='no', max_length=6, verbose_name='Были конфликты?'),
        ),
    ]
