# Generated by Django 3.2.7 on 2022-05-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0024_auto_20220407_2127'),
        ('verificationrequests', '0008_auto_20220429_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='tours_countries',
            field=models.ManyToManyField(blank=True, to='geoplaces.Country', verbose_name='В какие страны туры'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='tours_countries',
            field=models.ManyToManyField(blank=True, to='geoplaces.Country', verbose_name='В какие страны туры'),
        ),
    ]
