# Generated by Django 3.2.7 on 2022-06-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_expert_preferred_payment_method'),
        ('geoplaces', '0025_auto_20220511_0423'),
        ('verificationrequests', '0009_auto_20220501_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('passport_series', models.CharField(max_length=255, verbose_name='Паспорт серия')),
                ('passport_number', models.CharField(max_length=255, verbose_name='Паспорт номер')),
                ('passport_code_issued_by', models.CharField(max_length=25, verbose_name='Паспорт код подразделения')),
                ('passport_issued_by', models.CharField(max_length=255, verbose_name='Паспорт кем выдан')),
                ('passport_date', models.DateField(verbose_name='Паспорт дата выдачи')),
                ('license', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=3, verbose_name='Наличие лицензии')),
                ('commercial_tours', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=3, verbose_name='Коммерческие туры')),
                ('reviews_links', models.TextField(blank=True, null=True, verbose_name='Ссылки на отзывы')),
                ('tours_links', models.TextField(blank=True, null=True, verbose_name='Ссылки на туры')),
                ('conflicts', models.TextField(choices=[('yes', 'Да'), ('no', 'Нет')], default='no', max_length=3, verbose_name='Были конфликты?')),
                ('conflicts_review', models.TextField(blank=True, null=True, verbose_name='Описание конфликта')),
                ('legal_restrictions', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=3, verbose_name='Были конфликты?')),
                ('legal_restrictions_review', models.TextField(blank=True, null=True, verbose_name='Описание конфликта')),
                ('aproved', models.BooleanField(default=False)),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='individual_verification', to='accounts.expert', verbose_name='Эксперт')),
                ('residency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificationrequests_verificationrequest_citizenship', to='geoplaces.country', verbose_name='Резидент')),
                ('tours_countries', models.ManyToManyField(blank=True, to='geoplaces.Country', verbose_name='В какие страны туры')),
            ],
            options={
                'verbose_name': 'Запрос на проверку',
                'verbose_name_plural': 'Запросы на проверку',
            },
        ),
        migrations.RemoveField(
            model_name='legal',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='residency',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='tours_countries',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='expert',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
        migrations.DeleteModel(
            name='Legal',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
