# Generated by Django 3.2.7 on 2022-06-02 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_expert_preferred_payment_method'),
        ('verificationrequests', '0010_auto_20220602_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='residency',
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='expert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='accounts.expert', verbose_name='Эксперт'),
        ),
    ]
