# Generated by Django 3.2.7 on 2022-06-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0025_auto_20220511_0423'),
        ('verificationrequests', '0011_auto_20220602_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='residency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificationrequests_verificationrequest_citizenship', to='geoplaces.country', verbose_name='Резидент'),
        ),
    ]
