# Generated by Django 3.2.7 on 2022-06-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificationrequests', '0013_auto_20220602_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='commercial_tours_yearly',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Туры в год'),
        ),
    ]
