# Generated by Django 3.2.7 on 2022-07-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0028_auto_20220707_1629'),
        ('verificationrequests', '0014_verificationrequest_commercial_tours_yearly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='residency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificationrequests_verificationrequest_citizenship', to='geoplaces.destination', verbose_name='Резидент'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='tours_countries',
            field=models.ManyToManyField(blank=True, to='geoplaces.Destination', verbose_name='В какие страны туры'),
        ),
    ]
