# Generated by Django 3.2.7 on 2021-09-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное Имя'),
        ),
    ]
