# Generated by Django 3.2.7 on 2022-04-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='id tg сообщения'),
        ),
    ]
