# Generated by Django 3.2.7 on 2022-04-21 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supports', '0002_chatmessage_sender_chat_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='SupportChatMessage',
        ),
    ]
