# Generated by Django 3.2.7 on 2022-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0003_rename_chatmessage_supportchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ушла в работу'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыта в'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Открыта'), (2, 'В работе'), (3, 'Закрыта')], default=1, verbose_name='Статус'),
        ),
    ]
