# Generated by Django 3.2.7 on 2022-05-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0004_auto_20220421_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='stuff',
            new_name='staff',
        ),
    ]
