# Generated by Django 3.2.7 on 2022-05-02 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supports', '0005_rename_stuff_ticket_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_chats', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
