# Generated by Django 3.2.7 on 2022-05-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0006_alter_ticket_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['status', '-created_at'], 'verbose_name': 'Заявка в ТП', 'verbose_name_plural': 'Заявки в ТП'},
        ),
    ]
