# Generated by Django 3.2.7 on 2022-06-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Реферальные быллы'),
        ),
    ]
