# Generated by Django 3.2.7 on 2022-06-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0081_declinereason_staff'),
        ('referals', '0003_alter_referral_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_referrals', to='tours.tour'),
        ),
    ]
