# Generated by Django 3.2.7 on 2021-10-11 13:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teammember_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='about_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='about_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
