# Generated by Django 3.2.7 on 2021-10-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_options'),
        ('accounts', '0007_auto_20211011_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='languages',
        ),
        migrations.AddField(
            model_name='teammember',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='team_member', to='languages.Language', verbose_name='Языки'),
        ),
    ]
