# Generated by Django 3.2.7 on 2021-11-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_expert_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='tours_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
