# Generated by Django 3.2.7 on 2021-11-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_expert_tours_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во отзывов'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='tours_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг туров'),
        ),
    ]
