# Generated by Django 3.2.7 on 2021-12-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_tmb_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tmb_avatar',
        ),
    ]
