# Generated by Django 3.2.7 on 2022-02-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20220210_2118'),
        ('accounts', '0016_remove_user_tmb_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='languages_en',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='languages_ru',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='languages',
        ),
        migrations.AddField(
            model_name='expert',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='expert', to='languages.Language', verbose_name='Языки'),
        ),
    ]
