# Generated by Django 3.2.7 on 2022-03-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220213_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
    ]
