# Generated by Django 3.2.7 on 2022-03-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_teammember_is_expert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатели', 'verbose_name_plural': 'Покупатель'},
        ),
    ]
