# Generated by Django 3.2.7 on 2022-03-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='video',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
