# Generated by Django 3.2.7 on 2022-03-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_expert_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='midle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
    ]
