# Generated by Django 3.2.7 on 2022-04-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_teammember_midle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='commission',
            field=models.PositiveIntegerField(default=15, verbose_name='Комиссия'),
        ),
    ]
