# Generated by Django 3.2.7 on 2022-04-26 14:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_expert_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='languages',
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон'),
        ),
    ]
