# Generated by Django 3.2.7 on 2022-04-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20220426_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='bank_transaction',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='debet_card',
        ),
    ]
