# Generated by Django 3.2.7 on 2022-05-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_phoneconfirm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-id', 'expert'], 'verbose_name': 'Член команды', 'verbose_name_plural': 'Члены команды'},
        ),
    ]
