# Generated by Django 3.2.7 on 2022-05-31 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20220531_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее посещение'),
        ),
    ]
