# Generated by Django 3.2.7 on 2022-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_user_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='preferred_payment_method',
            field=models.IntegerField(choices=[(1, 'Дебетовая карта'), (2, 'Банковский перевод')], default=1, verbose_name='Способ выплаты'),
        ),
    ]
