# Generated by Django 3.2.7 on 2022-06-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_user_referals_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referals_score',
            new_name='referrals_score',
        ),
    ]
