# Generated by Django 3.2.7 on 2022-07-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0086_remove_tour_destination'),
        ('accounts', '0035_rename_referals_score_user_referrals_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorit_tours',
            field=models.ManyToManyField(related_name='users', to='tours.Tour', verbose_name='Избранные туры'),
        ),
    ]
