# Generated by Django 3.2.7 on 2022-07-14 15:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0086_remove_tour_destination'),
        ('geoplaces', '0029_auto_20220707_2016'),
        ('accounts', '0036_user_favorit_tours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyViewedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to='tours.tour')),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to='accounts.identifier')),
            ],
        ),
        migrations.AddField(
            model_name='identifier',
            name='recently_viewed_tours',
            field=models.ManyToManyField(related_name='uuid_by_tours', through='accounts.RecentlyViewedTour', to='tours.Tour', verbose_name='Просмотренные направления'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='viewed_destinations',
            field=models.ManyToManyField(related_name='uuid_by_destinations', to='geoplaces.Destination', verbose_name='Просмотренные направления'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_uuids',
            field=models.ManyToManyField(related_name='users', to='accounts.Identifier', verbose_name='UUIDs'),
        ),
    ]
