# Generated by Django 3.2.7 on 2022-07-14 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20220714_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_uuids',
        ),
        migrations.AddField(
            model_name='identifier',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_uuids', to=settings.AUTH_USER_MODEL),
        ),
    ]
