# Generated by Django 3.2.7 on 2022-07-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20220714_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorit_tours',
            new_name='favorite_tours',
        ),
    ]
