# Generated by Django 3.2.7 on 2021-10-08 09:50

from django.db import migrations, models
import django.db.models.deletion
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0001_initial'),
        ('accounts', '0004_auto_20210929_1453'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAdvanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время прибытия')),
                ('finish_time', models.TimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('instant_booking', models.BooleanField(default=False, verbose_name='Моментальное бронирование')),
                ('members_number', models.PositiveIntegerField(verbose_name='Колличество мест')),
                ('prepayment', models.PositiveIntegerField(default=15, verbose_name='Предоплата в %')),
                ('postpayment', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дни внесения полной суммы до старта')),
                ('week_recurrent', models.BooleanField(default=False, verbose_name='Повторять еженедельно')),
                ('month_recurrent', models.BooleanField(default=False, verbose_name='Повторять ежемесячно')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ['tour', '-id'], 'verbose_name': 'Фото тура', 'verbose_name_plural': 'Фотографии туров'},
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt текст'),
        ),
        migrations.AddField(
            model_name='tourdayimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt текст'),
        ),
        migrations.AddField(
            model_name='tourdayimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tourdayimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=tours.models.tour_image_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='tourdayimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tourdayimage',
            name='tour_day',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tourday', verbose_name='День тура'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt текст'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=tours.models.tour_image_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='TourBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draft', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('moderation', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('direct_link', models.BooleanField(default=False, verbose_name='Доступ по прямой ссылке')),
                ('additional_types', models.ManyToManyField(related_name='tours_by_additional_types', to='tours.TourType', verbose_name='Основной тип')),
                ('basic_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_basic_type', to='tours.tourtype', verbose_name='Основной тип')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='accounts.expert', verbose_name='Основной тип')),
                ('finish_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_finish_city', to='geoplaces.city', verbose_name='Город завершения путешествия')),
                ('finish_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_finish_country', to='geoplaces.country', verbose_name='Страна завершения путешествия')),
                ('finish_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_finish_region', to='geoplaces.region', verbose_name='Регион завершения путешествия')),
                ('start_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_start_city', to='geoplaces.city', verbose_name='Город начала путешествия')),
                ('start_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_start_country', to='geoplaces.country', verbose_name='Страна начала путешествия')),
                ('start_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_start_region', to='geoplaces.region', verbose_name='Регион начала путешествия')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.AddField(
            model_name='propertytype',
            name='tours',
            field=models.ManyToManyField(related_name='property_types', to='tours.TourBasic'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_images', to='tours.tourbasic', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='tours.tourbasic', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_days', to='tours.tourbasic'),
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
