# Generated by Django 3.2.7 on 2021-10-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20211008_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touradvanced',
            name='month_recurrent',
        ),
        migrations.RemoveField(
            model_name='touradvanced',
            name='week_recurrent',
        ),
        migrations.AddField(
            model_name='tourbasic',
            name='month_recurrent',
            field=models.BooleanField(default=False, verbose_name='Повторять ежемесячно'),
        ),
        migrations.AddField(
            model_name='tourbasic',
            name='week_recurrent',
            field=models.BooleanField(default=False, verbose_name='Повторять еженедельно'),
        ),
    ]
