# Generated by Django 3.2.7 on 2021-10-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teammember'),
        ('tours', '0003_auto_20211008_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='touradvanced',
            name='basic_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advanced_tours', to='tours.tourbasic', verbose_name='Тур основа'),
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advanced_tours', to='accounts.teammember', verbose_name='Гид'),
        ),
        migrations.AlterField(
            model_name='tourbasic',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='accounts.expert', verbose_name='Эксперт'),
        ),
    ]
