# Generated by Django 3.2.7 on 2021-10-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20211011_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touradvanced',
            options={'verbose_name': 'Тип размещения', 'verbose_name_plural': 'Типы размещения'},
        ),
        migrations.AlterModelOptions(
            name='tourbasic',
            options={'verbose_name': 'Тур основа', 'verbose_name_plural': 'Туры основа'},
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='finish_date',
            field=models.TimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='start_date',
            field=models.TimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='touradvanced',
            name='basic_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_tours', to='tours.tourbasic', verbose_name='Тур основа'),
        ),
        migrations.AlterField(
            model_name='touradvanced',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время старта'),
        ),
    ]
