# Generated by Django 3.2.7 on 2021-10-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('tours', '0005_auto_20211011_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touradvanced',
            options={'verbose_name': 'Тур доп сведения', 'verbose_name_plural': 'Туры доп сведения'},
        ),
        migrations.AlterModelOptions(
            name='tourdayimage',
            options={'verbose_name': 'Фото дня тура', 'verbose_name_plural': 'Фото дней туров'},
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advanced_tours', to='currencies.currency', verbose_name='Влюта'),
        ),
        migrations.AlterField(
            model_name='tourbasic',
            name='additional_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='tours_by_additional_types', to='tours.TourType', verbose_name='Дополнительные типы тура'),
        ),
        migrations.AlterField(
            model_name='tourbasic',
            name='basic_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_basic_type', to='tours.tourtype', verbose_name='Основной тип тура'),
        ),
    ]
