# Generated by Django 3.2.7 on 2021-10-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20211014_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourday',
            unique_together={('number', 'tour')},
        ),
    ]
