# Generated by Django 3.2.7 on 2021-10-14 12:24

from django.db import migrations, models
import django.db.models.deletion
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tourday_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourExcludedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_excluded_services', to='tours.tourbasic', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Входит в стоимость',
                'verbose_name_plural': 'Входит в стоимость',
            },
        ),
        migrations.CreateModel(
            name='TourImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_impressions', to='tours.tourbasic', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Главное впечатление',
                'verbose_name_plural': 'Главные впечатления',
            },
        ),
        migrations.CreateModel(
            name='TourIncludedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_included_services', to='tours.tourbasic', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Входит в стоимость',
                'verbose_name_plural': 'Входит в стоимость',
            },
        ),
        migrations.CreateModel(
            name='TourPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(max_length=255, upload_to=tours.models.tour_image_path, verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt текст')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_property_images', to='tours.tourbasic', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Тип размещения',
                'verbose_name_plural': 'Типы размещения',
            },
        ),
        migrations.CreateModel(
            name='TourPropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tours', models.ManyToManyField(related_name='tour_property_types', to='tours.TourBasic')),
            ],
            options={
                'verbose_name': 'Тип размещения',
                'verbose_name_plural': 'Типы размещения',
            },
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='tours',
        ),
        migrations.AlterField(
            model_name='tourday',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_days', to='tours.tourbasic', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourdayimage',
            name='tour_day',
            field=models.OneToOneField(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_day_image', to='tours.tourday', verbose_name='День тура'),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
    ]
