# Generated by Django 3.2.7 on 2021-10-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('tours', '0009_auto_20211014_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpropertyimage',
            options={'verbose_name': 'Фото размещения', 'verbose_name_plural': 'Фотографии размещений'},
        ),
        migrations.AlterField(
            model_name='touradvanced',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advanced_tours', to='currencies.currency', verbose_name='Валюта'),
        ),
    ]
