# Generated by Django 3.2.7 on 2021-10-14 15:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_options'),
        ('currencies', '0001_initial'),
        ('tours', '0010_auto_20211014_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbasic',
            name='direct_link',
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='direct_link',
            field=models.BooleanField(default=False, verbose_name='Доступ по прямой ссылке'),
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='flight_included',
            field=models.BooleanField(default=False, verbose_name='Перелет включен'),
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='is_guaranteed',
            field=models.BooleanField(default=False, verbose_name='Тур гарантирован'),
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='advanced_tours', to='languages.Language', verbose_name='Языки тура'),
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='scouting',
            field=models.BooleanField(default=False, verbose_name='Разведка'),
        ),
        migrations.AddField(
            model_name='tourbasic',
            name='cancellation_terms',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия отмены'),
        ),
        migrations.AddField(
            model_name='tourbasic',
            name='comfort_level',
            field=models.PositiveIntegerField(default=3, verbose_name='Уровень комфорта'),
        ),
        migrations.AddField(
            model_name='tourbasic',
            name='difficulty_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание сложностей'),
        ),
        migrations.AddField(
            model_name='tourbasic',
            name='difficulty_level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень сложности'),
        ),
        migrations.CreateModel(
            name='TourAddetionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_addetional_service', to='currencies.currency', verbose_name='Валюта')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_addetional_services', to='tours.tourbasic', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительнае услуги',
            },
        ),
    ]
