# Generated by Django 3.2.7 on 2021-10-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20211014_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbasic',
            name='animals_not_exploited',
            field=models.BooleanField(default=False, verbose_name='Животные не эксплуатируются'),
        ),
        migrations.AddField(
            model_name='tourbasic',
            name='babies_alowed',
            field=models.BooleanField(default=False, verbose_name='Можно с маленькими детьми'),
        ),
        migrations.AlterField(
            model_name='tourbasic',
            name='additional_types',
            field=models.ManyToManyField(blank=True, related_name='tours_by_additional_types', to='tours.TourType', verbose_name='Дополнительные типы тура'),
        ),
        migrations.AlterField(
            model_name='tourbasic',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
