# Generated by Django 3.2.7 on 2021-10-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20211014_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourexcludedservice',
            options={'verbose_name': 'Не входит в стоимость', 'verbose_name_plural': 'Не входит в стоимость'},
        ),
    ]
