# Generated by Django 3.2.7 on 2021-10-20 13:07

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_alter_tourexcludedservice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbasic',
            name='wallpaper',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=tours.models.tour_image_path, verbose_name='Главное фото'),
        ),
    ]
