# Generated by Django 3.2.7 on 2021-11-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_tourbasic_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touradvanced',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='touradvanced',
            name='start_date',
        ),
    ]
