# Generated by Django 3.2.7 on 2021-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_auto_20211117_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='touradvanced',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
