# Generated by Django 3.2.7 on 2021-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_tourday_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touraddetionalservice',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='touradvanced',
            name='cost',
        ),
        migrations.AddField(
            model_name='touraddetionalservice',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='touradvanced',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
