# Generated by Django 3.2.7 on 2021-12-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0024_remove_touradvanced_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='touradvanced',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность тура в днях'),
        ),
    ]
