# Generated by Django 3.2.7 on 2021-12-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_touradvanced_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='touradvanced',
            name='vacants_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество свободных мест'),
        ),
        migrations.AlterField(
            model_name='touradvanced',
            name='members_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество мест'),
        ),
    ]
