# Generated by Django 3.2.7 on 2022-02-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0026_auto_20211223_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbasic',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
    ]
