# Generated by Django 3.2.7 on 2022-02-10 14:28

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0027_alter_tourbasic_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('is_active', models.BooleanField(default=False)),
                ('on_moderation', models.BooleanField(default=False, verbose_name='На модерации')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Кол-во отзывов')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('wallpaper', models.ImageField(blank=True, max_length=255, null=True, upload_to=tours.models.tour_image_path, verbose_name='Главное фото')),
                ('week_recurrent', models.BooleanField(default=False, verbose_name='Повторять еженедельно')),
                ('month_recurrent', models.BooleanField(default=False, verbose_name='Повторять ежемесячно')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание тура')),
                ('plan', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Чем займемся')),
                ('cancellation_terms', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия отмены')),
                ('difficulty_level', models.PositiveIntegerField(default=1, verbose_name='Уровень сложности')),
                ('difficulty_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание сложностей')),
                ('comfort_level', models.PositiveIntegerField(default=3, verbose_name='Уровень комфорта')),
                ('babies_alowed', models.BooleanField(default=False, verbose_name='Можно с маленькими детьми')),
                ('animals_not_exploited', models.BooleanField(default=False, verbose_name='Животные не эксплуатируются')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность тура в днях')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время старта')),
                ('finish_time', models.TimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('direct_link', models.BooleanField(default=False, verbose_name='Доступ по прямой ссылке')),
                ('instant_booking', models.BooleanField(default=False, verbose_name='Моментальное бронирование')),
                ('members_number', models.PositiveIntegerField(default=0, verbose_name='Колличество мест')),
                ('vacants_number', models.PositiveIntegerField(default=0, verbose_name='Колличество свободных мест')),
                ('prepayment', models.PositiveIntegerField(default=15, verbose_name='Предоплата в %')),
                ('postpayment', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дни внесения полной суммы до старта')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость со скидкой')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('is_guaranteed', models.BooleanField(default=False, verbose_name='Тур гарантирован')),
                ('flight_included', models.BooleanField(default=False, verbose_name='Перелет включен')),
                ('scouting', models.BooleanField(default=False, verbose_name='Разведка')),
            ],
            options={
                'verbose_name': 'Тур основа',
                'verbose_name_plural': 'Туры основа',
            },
        ),
        migrations.RemoveField(
            model_name='touradvanced',
            name='basic_tour',
        ),
        migrations.RemoveField(
            model_name='touradvanced',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='touradvanced',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='touradvanced',
            name='team_member',
        ),
        migrations.RemoveField(
            model_name='tourbasic',
            name='additional_types',
        ),
        migrations.RemoveField(
            model_name='tourbasic',
            name='basic_type',
        ),
        migrations.RemoveField(
            model_name='tourbasic',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='tourbasic',
            name='finish_city',
        ),
        migrations.RemoveField(
            model_name='tourbasic',
            name='finish_country',
        ),
        migrations.RemoveField(
            model_name='tourbasic',
            name='finish_region',
        ),
        migrations.RemoveField(
            model_name='tourbasic',
            name='start_city',
        ),
        migrations.RemoveField(
            model_name='tourbasic',
            name='start_country',
        ),
        migrations.RemoveField(
            model_name='tourbasic',
            name='start_region',
        ),
    ]
