# Generated by Django 3.2.7 on 2022-02-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0028_auto_20220210_1728'),
        ('reviews', '0003_alter_tourreview_tour'),
        ('languages', '0002_alter_language_options'),
        ('accounts', '0016_remove_user_tmb_avatar'),
        ('orders', '0002_alter_order_tour'),
        ('geoplaces', '0003_auto_20211014_1416'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourAdvanced',
        ),
        migrations.AddField(
            model_name='tour',
            name='additional_types',
            field=models.ManyToManyField(blank=True, related_name='tours_by_additional_types', to='tours.TourType', verbose_name='Дополнительные типы тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='basic_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_basic_type', to='tours.tourtype', verbose_name='Основной тип тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advanced_tours', to='currencies.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='tour',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='accounts.expert', verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='tour',
            name='finish_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_finish_city', to='geoplaces.city', verbose_name='Город завершения путешествия'),
        ),
        migrations.AddField(
            model_name='tour',
            name='finish_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_finish_country', to='geoplaces.country', verbose_name='Страна завершения путешествия'),
        ),
        migrations.AddField(
            model_name='tour',
            name='finish_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_finish_region', to='geoplaces.region', verbose_name='Регион завершения путешествия'),
        ),
        migrations.AddField(
            model_name='tour',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='advanced_tours', to='languages.Language', verbose_name='Языки тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_start_city', to='geoplaces.city', verbose_name='Город начала путешествия'),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_start_country', to='geoplaces.country', verbose_name='Страна начала путешествия'),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_start_region', to='geoplaces.region', verbose_name='Регион начала путешествия'),
        ),
        migrations.AddField(
            model_name='tour',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advanced_tours', to='accounts.teammember', verbose_name='Гид'),
        ),
        migrations.AlterField(
            model_name='touraddetionalservice',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_addetional_services', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_days', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourexcludedservice',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_excluded_services', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_images', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourimpression',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_impressions', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourincludedservice',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_included_services', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourpropertyimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_property_images', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourpropertytype',
            name='tours',
            field=models.ManyToManyField(related_name='tour_property_types', to='tours.Tour'),
        ),
        migrations.DeleteModel(
            name='TourBasic',
        ),
    ]
