# Generated by Django 3.2.7 on 2022-02-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0029_auto_20220210_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourday',
            options={'ordering': ['id'], 'verbose_name': 'День тура', 'verbose_name_plural': 'Дни туров'},
        ),
        migrations.RemoveField(
            model_name='tourdayimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tourdayimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tourdayimage',
            name='tour_day',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_day_images', to='tours.tourday', verbose_name='День тура'),
        ),
        migrations.AlterUniqueTogether(
            name='tourday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tourday',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tourday',
            name='number',
        ),
    ]
