# Generated by Django 3.2.7 on 2022-02-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20220210_2118'),
        ('accounts', '0017_auto_20220213_2123'),
        ('currencies', '0001_initial'),
        ('tours', '0031_auto_20220213_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='currencies.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='tours', to='languages.Language', verbose_name='Языки тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='accounts.teammember', verbose_name='Гид'),
        ),
    ]
