# Generated by Django 3.2.7 on 2022-02-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0032_auto_20220214_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='flight_included',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Перелет включен'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_guaranteed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Тур гарантирован'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='scouting',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Разведка'),
        ),
    ]
