# Generated by Django 3.2.7 on 2022-02-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('tours', '0033_auto_20220214_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='postpayment',
            new_name='postpay_days_before_start',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='prepayment',
        ),
        migrations.AddField(
            model_name='tour',
            name='postpay_on_start_day',
            field=models.BooleanField(default=False, verbose_name='Постоплата в день старта'),
        ),
        migrations.AddField(
            model_name='tour',
            name='prepay_amount',
            field=models.PositiveIntegerField(default=15, verbose_name='Размер предоплаты'),
        ),
        migrations.AddField(
            model_name='tour',
            name='prepay_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_prepay_currency', to='currencies.currency', verbose_name='Валюта предоплаты'),
        ),
        migrations.AddField(
            model_name='tour',
            name='prepay_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Действует до'),
        ),
        migrations.AddField(
            model_name='tour',
            name='prepay_in_prc',
            field=models.BooleanField(default=True, verbose_name='Предоплата в процентах'),
        ),
        migrations.AddField(
            model_name='tour',
            name='prepay_starts',
            field=models.DateField(blank=True, null=True, verbose_name='Действует с'),
        ),
    ]
