# Generated by Django 3.2.7 on 2022-02-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0035_tour_price_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='accomodation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='РАЗМЕЩЕНИЕ'),
        ),
        migrations.AddField(
            model_name='tour',
            name='age_ends',
            field=models.PositiveIntegerField(blank=True, default=85, null=True, verbose_name='Мин возраст участника тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='age_starts',
            field=models.PositiveIntegerField(blank=True, default=15, null=True, verbose_name='Мин возраст участника тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование отеля'),
        ),
        migrations.AddField(
            model_name='tour',
            name='media_link',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Ссылка на видео тура'),
        ),
        migrations.AlterField(
            model_name='tourimpression',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_impressions', to='tours.tour', verbose_name='Тур'),
        ),
    ]
