# Generated by Django 3.2.7 on 2022-02-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0036_auto_20220214_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpropertytype',
            name='tours',
            field=models.ManyToManyField(related_name='tour_property_types', to='tours.Tour', verbose_name='Тур'),
        ),
    ]
