# Generated by Django 3.2.7 on 2022-02-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0037_alter_tourpropertytype_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpropertytype',
            name='tours',
            field=models.ManyToManyField(blank=True, related_name='tour_property_types', to='tours.Tour', verbose_name='Тур'),
        ),
    ]
