# Generated by Django 3.2.7 on 2022-02-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220213_2123'),
        ('tours', '0040_tour_air_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='prepay_finish',
            new_name='discount_finish',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='prepay_starts',
            new_name='discount_starts',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='reviews_count',
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_in_prc',
            field=models.BooleanField(default=True, verbose_name='Скидка в процентах'),
        ),
        migrations.CreateModel(
            name='TourBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Кол-во отзывов')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='accounts.expert', verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Основа тура',
                'verbose_name_plural': 'Основы туров',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourbasic', verbose_name='Основа тура'),
        ),
    ]
