# Generated by Django 3.2.7 on 2022-02-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0041_auto_20220227_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbasic',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
