# Generated by Django 3.2.7 on 2022-02-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0043_auto_20220227_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='accomodation',
        ),
        migrations.CreateModel(
            name='TourAccomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tours', models.ManyToManyField(blank=True, related_name='accomodation', to='tours.Tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Размещения',
                'verbose_name_plural': 'Размещение',
            },
        ),
    ]
