# Generated by Django 3.2.7 on 2022-02-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0046_auto_20220227_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touraccomodation',
            name='tours',
        ),
        migrations.RemoveField(
            model_name='tourpropertytype',
            name='tours',
        ),
        migrations.AddField(
            model_name='tour',
            name='accomodation',
            field=models.ManyToManyField(blank=True, related_name='accomodation', to='tours.TourAccomodation', verbose_name='Размещения'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_property_types',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.TourPropertyType', verbose_name='Типы размещения'),
        ),
    ]
