# Generated by Django 3.2.7 on 2022-03-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0047_auto_20220228_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ['-id'], 'verbose_name': 'Фото тура', 'verbose_name_plural': 'Фотографии туров'},
        ),
        migrations.RemoveField(
            model_name='touraddetionalservice',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourday',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourexcludedservice',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourimage',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourimpression',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourincludedservice',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourplan',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourpropertyimage',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='main_impressions',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.TourImpression', verbose_name='Главные впечатления'),
        ),
        migrations.AddField(
            model_name='tour',
            name='plan',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.TourPlan', verbose_name='Чем займемся'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_addetional_services',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.TourAddetionalService', verbose_name='Дополнительные услуги'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_days',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.TourDay', verbose_name='Дни тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_excluded_services',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.TourExcludedService', verbose_name='Не включенные услуги'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_images',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.TourImage', verbose_name='Галерея тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_property_images',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.TourPropertyImage', verbose_name='Фото размещений'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='accomodation',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.TourAccomodation', verbose_name='Размещения'),
        ),
        migrations.RemoveField(
            model_name='tourdayimage',
            name='tour_day',
        ),
        migrations.AddField(
            model_name='tourdayimage',
            name='tour_day',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='tour_day_images', to='tours.TourDay', verbose_name='День тура'),
        ),
    ]
