# Generated by Django 3.2.7 on 2022-03-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0048_auto_20220302_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_included_services',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.TourIncludedService', verbose_name='Включенные услуги'),
        ),
    ]
