# Generated by Django 3.2.7 on 2022-03-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0049_tour_tour_included_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='main_impressions',
        ),
        migrations.AddField(
            model_name='tour',
            name='main_impressions',
            field=models.JSONField(blank=True, null=True, verbose_name='Главные впечатления'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_excluded_services',
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_excluded_services',
            field=models.JSONField(blank=True, null=True, verbose_name='Не включенные услуги'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_included_services',
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_included_services',
            field=models.JSONField(blank=True, null=True, verbose_name='Включенные услуги'),
        ),
    ]
