# Generated by Django 3.2.7 on 2022-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0050_auto_20220302_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourdayimage',
            name='tour_day',
        ),
        migrations.AddField(
            model_name='tourday',
            name='tour_day_images',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='tour_day', to='tours.TourDay', verbose_name='День тура'),
        ),
    ]
