# Generated by Django 3.2.7 on 2022-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0051_auto_20220302_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourday',
            name='tour_day_images',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='tour_day', to='tours.TourDay', verbose_name='Фотографии дня'),
        ),
    ]
