# Generated by Django 3.2.7 on 2022-03-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0052_alter_tourday_tour_day_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourday',
            name='tour_day_images',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='tour_day', to='tours.TourDayImage', verbose_name='Фотографии дня'),
        ),
    ]
