# Generated by Django 3.2.7 on 2022-03-03 16:18

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0053_alter_tourday_tour_day_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=tours.models.tour_image_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'День тура',
                'verbose_name_plural': 'Дни туров',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='tour',
            name='plan',
        ),
        migrations.AddField(
            model_name='tour',
            name='plan',
            field=models.JSONField(blank=True, null=True, verbose_name='Чем займемся'),
        ),
        migrations.DeleteModel(
            name='TourPlan',
        ),
    ]
