# Generated by Django 3.2.7 on 2022-03-04 13:20

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0055_auto_20220303_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuestGuideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=tours.models.tour_image_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото приглашенного гида',
                'verbose_name_plural': 'Фотографии приглашенных гидов',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='tourdayimage',
            options={'verbose_name': 'Фото дня тура', 'verbose_name_plural': 'Фотографии дней туров'},
        ),
        migrations.AlterModelOptions(
            name='tourplanimage',
            options={'ordering': ['id'], 'verbose_name': 'Фото чем займемся', 'verbose_name_plural': 'Фотографии чем займемся'},
        ),
        migrations.AddField(
            model_name='tour',
            name='guest_guide',
            field=models.JSONField(blank=True, null=True, verbose_name='Приглашенный гид'),
        ),
    ]
