# Generated by Django 3.2.7 on 2022-03-05 02:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0056_auto_20220304_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='guest_requirements',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Требования к гостю'),
        ),
        migrations.AddField(
            model_name='tour',
            name='important_to_know_comments',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Важно знать (коментарии)'),
        ),
    ]
