# Generated by Django 3.2.7 on 2022-03-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customer_options'),
        ('tours', '0056_auto_20220304_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguestguideimage',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_guest_guide_images', to='accounts.expert'),
        ),
    ]
