# Generated by Django 3.2.7 on 2022-03-05 12:46

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0058_auto_20220305_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourWallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=tours.models.tour_image_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Обложка тура',
                'verbose_name_plural': 'Обложки тура',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='tour',
            name='wallpaper',
        ),
    ]
