# Generated by Django 3.2.7 on 2022-03-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0058_auto_20220305_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touraddetionalservice',
            name='currency',
        ),
        migrations.DeleteModel(
            name='TourExcludedService',
        ),
        migrations.DeleteModel(
            name='TourImpression',
        ),
        migrations.DeleteModel(
            name='TourIncludedService',
        ),
        migrations.DeleteModel(
            name='TourAddetionalService',
        ),
    ]
