# Generated by Django 3.2.7 on 2022-03-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0059_auto_20220305_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='wallpaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='tours.tourwallpaper', verbose_name='Главное фото'),
        ),
    ]
