# Generated by Django 3.2.7 on 2022-03-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customer_options'),
        ('tours', '0060_tour_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourwallpaper',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_wallpapers', to='accounts.expert'),
        ),
        migrations.AddField(
            model_name='tourwallpaper',
            name='tour_basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_wallpapers', to='tours.tourbasic', verbose_name='Основа тура'),
        ),
    ]
