# Generated by Django 3.2.7 on 2022-03-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0061_auto_20220305_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourwallpaper',
            old_name='image',
            new_name='wallpaper',
        ),
    ]
