# Generated by Django 3.2.7 on 2022-03-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0062_rename_image_tourwallpaper_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='postpay_days_before_start',
            field=models.PositiveIntegerField(blank=True, default=3, null=True, verbose_name='Дни внесения полной суммы до старта'),
        ),
    ]
