# Generated by Django 3.2.7 on 2022-03-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0010_auto_20220329_1707'),
        ('tours', '0063_alter_tour_postpay_days_before_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='finish_russian_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_finish_russian_region', to='geoplaces.countryregion', verbose_name='Российский регион завершения путешествия'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_russian_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_start_russian_region', to='geoplaces.countryregion', verbose_name='Российский регион начала путешествия'),
        ),
    ]
