# Generated by Django 3.2.7 on 2022-04-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0067_alter_tour_postpay_days_before_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Важно знать',
                'verbose_name_plural': 'Важно знать',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Important',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('required', models.BooleanField(default=False)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='important_to_know', to='tours.tour')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
