# Generated by Django 3.2.7 on 2022-04-11 19:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0068_important_importanttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='completed_sections',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=None), blank=True, default=list, size=1),
        ),
    ]
