# Generated by Django 3.2.7 on 2022-04-11 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0069_tour_completed_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='completed_sections',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=None), blank=True, default=list, size=None),
        ),
    ]
