# Generated by Django 3.2.7 on 2022-04-11 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0070_alter_tour_completed_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='completed_sections',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, default=list, size=None),
        ),
    ]
