# Generated by Django 3.2.7 on 2022-04-13 19:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0072_alter_tour_media_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='important_to_know_comments',
        ),
        migrations.AddField(
            model_name='tour',
            name='key_features',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ключевые особенности'),
        ),
        migrations.AddField(
            model_name='tour',
            name='new_to_see',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Что нового я увижу'),
        ),
        migrations.AddField(
            model_name='tour',
            name='take_with',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Что взять с собой'),
        ),
    ]
