# Generated by Django 3.2.7 on 2022-04-22 21:29

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0075_tour_postpay_days_before_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='booking_delay',
            field=models.DurationField(default=tours.models.get_booking_delay),
        ),
    ]
