# Generated by Django 3.2.7 on 2022-05-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0077_auto_20220425_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='map',
            field=models.JSONField(blank=True, null=True, verbose_name='Карта'),
        ),
    ]
