# Generated by Django 3.2.7 on 2022-05-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0078_tour_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratedTour',
            fields=[
            ],
            options={
                'verbose_name': 'Тур на модерации',
                'verbose_name_plural': 'Туры на модерации',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tours.tour',),
        ),
    ]
