# Generated by Django 3.2.7 on 2022-06-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0079_moderatedtour'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclineReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(verbose_name='Причина отказа')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decline_reasons', to='tours.tour')),
            ],
        ),
    ]
