# Generated by Django 3.2.7 on 2022-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0082_auto_20220705_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbasic',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
