# Generated by Django 3.2.7 on 2022-07-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0027_destination'),
        ('tours', '0083_alter_tourbasic_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='geoplaces.destination', verbose_name='Направление'),
        ),
    ]
