# Generated by Django 3.2.7 on 2022-07-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0028_auto_20220707_2016'),
        ('tours', '0084_tour_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='finish_country',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='finish_russian_region',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_country',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_russian_region',
        ),
        migrations.AddField(
            model_name='tour',
            name='finish_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_finish_destination', to='geoplaces.destination', verbose_name='Направление завершения путешествия'),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours_by_start_destination', to='geoplaces.destination', verbose_name='Направление начала путешествия'),
        ),
    ]
