# Generated by Django 3.2.7 on 2022-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0086_remove_tour_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='watched',
        ),
        migrations.AddField(
            model_name='tour',
            name='views_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Просмотры'),
        ),
    ]
