# Generated by Django 3.2.7 on 2022-04-26 14:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('docs_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('docs_meta_tag', models.TextField(blank=True, max_length=255, null=True, verbose_name='Мета теги')),
                ('docs_body', ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Текст')),
            ],
        ),
    ]
