# Generated by Django 3.2.7 on 2022-04-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_legaldocument_docs_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldocument',
            options={'verbose_name': 'Юр документ', 'verbose_name_plural': 'Юр документы'},
        ),
    ]
