# Generated by Django 3.2.7 on 2022-04-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_legaldocument_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldocument',
            options={'ordering': ['docs_name'], 'verbose_name': 'Юр документ', 'verbose_name_plural': 'Юр документы'},
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='docs_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='docs_slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='slug'),
        ),
    ]
