# Generated by Django 3.2.7 on 2022-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='sign',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Знак'),
        ),
    ]
