# Generated by Django 3.2.7 on 2022-04-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_bik', models.CharField(max_length=255, verbose_name='БИК')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bank_account', models.CharField(max_length=255, verbose_name='Кор счет')),
                ('bank_inn', models.CharField(max_length=255, verbose_name='ИНН Банка')),
                ('bank_kpp', models.CharField(max_length=255, verbose_name='КПП Банка')),
                ('bank_payment_reason', models.CharField(max_length=255, verbose_name='КПП Банка')),
                ('recipient_inn', models.CharField(max_length=255, verbose_name='ИНН Получателя')),
                ('recipient_account', models.CharField(max_length=255, verbose_name='Р/С Получателя')),
                ('recipient_ogrn', models.CharField(max_length=255, verbose_name='ОГРН Получателя')),
                ('recipient_kpp', models.CharField(max_length=255, verbose_name='КПП Получателя')),
                ('recipient_status', models.CharField(max_length=255, verbose_name='Статус')),
                ('recipient_registration_date', models.DateField(max_length=255, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Банковский перевод',
                'verbose_name_plural': 'Банковские переводы',
            },
        ),
        migrations.CreateModel(
            name='DebetCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_bik', models.CharField(max_length=255, verbose_name='БИК')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bank_account', models.CharField(max_length=255, verbose_name='Кор счет')),
                ('bank_inn', models.CharField(max_length=255, verbose_name='ИНН Банка')),
                ('bank_kpp', models.CharField(max_length=255, verbose_name='КПП Банка')),
                ('bank_payment_reason', models.CharField(max_length=255, verbose_name='КПП Банка')),
                ('recipient_full_name', models.CharField(max_length=255, verbose_name='Получатель(ФИО)')),
            ],
            options={
                'verbose_name': 'Дебетовая карта',
                'verbose_name_plural': 'Дебетовые карты',
            },
        ),
    ]
