# Generated by Django 3.2.7 on 2022-04-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20220427_1429'),
        ('bankdetails', '0002_auto_20220426_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='expert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transaction', to='accounts.expert', verbose_name='expert'),
        ),
        migrations.AddField(
            model_name='debetcard',
            name='expert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debet_card', to='accounts.expert', verbose_name='expert'),
        ),
    ]
