# Generated by Django 3.2.7 on 2022-04-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0003_auto_20220427_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='recipient_legal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр адрес'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование юр лица'),
        ),
    ]
