# Generated by Django 3.2.7 on 2022-04-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0024_auto_20220407_2127'),
        ('bankdetails', '0005_auto_20220427_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='billing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geoplaces.country', verbose_name='Страна платежного адреса'),
        ),
        migrations.AddField(
            model_name='debetcard',
            name='billing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geoplaces.country', verbose_name='Страна платежного адреса'),
        ),
    ]
