# Generated by Django 3.2.7 on 2022-06-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0006_auto_20220428_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debetcard',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='debetcard',
            name='expert',
        ),
        migrations.DeleteModel(
            name='BankTransaction',
        ),
        migrations.DeleteModel(
            name='DebetCard',
        ),
    ]
