# Generated by Django 3.2.7 on 2022-06-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0033_expert_preferred_payment_method'),
        ('bankdetails', '0007_auto_20220602_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_bik', models.CharField(max_length=9, verbose_name='БИК')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bank_account', models.CharField(max_length=255, verbose_name='Кор счет')),
                ('bank_inn', models.CharField(max_length=255, verbose_name='ИНН Банка')),
                ('bank_kpp', models.CharField(max_length=255, verbose_name='КПП Банка')),
                ('recipient_inn', models.CharField(max_length=255, verbose_name='ИНН Получателя')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Наименование юр лица')),
                ('recipient_account', models.CharField(max_length=255, verbose_name='Р/С Получателя')),
                ('recipient_ogrn', models.CharField(max_length=255, verbose_name='ОГРН Получателя')),
                ('recipient_legal_address', models.CharField(max_length=255, verbose_name='Юр адрес')),
                ('recipient_real_address', models.CharField(max_length=255, verbose_name='Фактический адрес')),
                ('recipient_kpp', models.CharField(max_length=255, verbose_name='КПП Получателя')),
                ('recipient_status', models.CharField(max_length=255, verbose_name='Статус')),
                ('recipient_registration_date', models.DateField(max_length=255, verbose_name='Дата регистрации')),
                ('payment_reason', models.CharField(max_length=255, verbose_name='КПП Банка')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='accounts.expert', verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Банковский перевод',
                'verbose_name_plural': 'Банковские переводы',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='scans')),
                ('bank_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='bankdetails.banktransaction')),
            ],
            options={
                'verbose_name': 'Скан документа',
                'verbose_name_plural': 'Сканы документов',
            },
        ),
        migrations.CreateModel(
            name='DebetCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_bik', models.CharField(max_length=9, verbose_name='БИК')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bank_account', models.CharField(max_length=255, verbose_name='Кор счет')),
                ('bank_inn', models.CharField(max_length=255, verbose_name='ИНН Банка')),
                ('bank_kpp', models.CharField(max_length=255, verbose_name='КПП Банка')),
                ('payment_reason', models.CharField(max_length=255, verbose_name='КПП Банка')),
                ('recipient_account', models.CharField(max_length=255, verbose_name='Р/С Получателя')),
                ('recipient_full_name', models.CharField(max_length=255, verbose_name='Получатель(ФИО)')),
                ('expert', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debet_card', to='accounts.expert', verbose_name='expert')),
            ],
            options={
                'verbose_name': 'Дебетовая карта',
                'verbose_name_plural': 'Дебетовые карты',
            },
        ),
    ]
