# Generated by Django 3.2.7 on 2022-06-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0010_auto_20220602_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='transaction_recipient_kpp',
        ),
    ]
