# Generated by Django 3.2.7 on 2022-06-03 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_expert_preferred_payment_method'),
        ('bankdetails', '0011_remove_banktransaction_transaction_recipient_kpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='expert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transaction', to='accounts.expert', verbose_name='Эксперт'),
        ),
    ]
