# Generated by Django 3.2.7 on 2021-11-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_expert_rating'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tours_reviews', to='accounts.customer', verbose_name='Путешественник'),
        ),
    ]
