# Generated by Django 3.2.7 on 2022-05-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatmessage_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
    ]
