# Generated by Django 3.2.7 on 2022-05-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
