# Generated by Django 3.2.7 on 2021-10-14 10:13

from django.db import migrations, models
import geoplaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=geoplaces.models.geo_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=geoplaces.models.geo_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=geoplaces.models.geo_path, verbose_name='Фото'),
        ),
    ]
