# Generated by Django 3.2.7 on 2021-10-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0002_auto_20211014_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt текст'),
        ),
        migrations.AddField(
            model_name='country',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt текст'),
        ),
        migrations.AddField(
            model_name='region',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt текст'),
        ),
    ]
