# Generated by Django 3.2.7 on 2022-02-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0004_auto_20220213_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='russianregion',
            options={'verbose_name': 'Регион России', 'verbose_name_plural': 'Регионы России'},
        ),
    ]
