# Generated by Django 3.2.7 on 2022-02-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0005_alter_russianregion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='forein_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сторонний ключ'),
        ),
        migrations.AddField(
            model_name='country',
            name='forein_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сторонний ключ'),
        ),
        migrations.AddField(
            model_name='russianregion',
            name='forein_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сторонний ключ'),
        ),
    ]
