# Generated by Django 3.2.7 on 2022-02-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0006_auto_20220213_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='forein_id',
            new_name='foreign_id',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='forein_id',
            new_name='foreign_id',
        ),
        migrations.RenameField(
            model_name='russianregion',
            old_name='forein_id',
            new_name='foreign_id',
        ),
    ]
