# Generated by Django 3.2.7 on 2022-02-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0007_auto_20220213_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='russian_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geoplaces.russianregion', verbose_name='Регион России'),
        ),
    ]
