# Generated by Django 3.2.7 on 2022-03-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0008_alter_city_russian_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион Мира', 'verbose_name_plural': 'Регионы Мира'},
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='geoplaces.region', verbose_name='Регион Мира'),
        ),
    ]
