# Generated by Django 3.2.7 on 2022-03-29 14:07

from django.db import migrations, models
import django.db.models.deletion
import geoplaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0009_auto_20220329_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('foreign_id', models.IntegerField(blank=True, null=True, verbose_name='Сторонний ключ')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=geoplaces.models.geo_path, verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt текст')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_regions', to='geoplaces.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион Страны',
                'verbose_name_plural': 'Регионы Страны',
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='russian_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geoplaces.countryregion', verbose_name='Регион России'),
        ),
    ]
