# Generated by Django 3.2.7 on 2022-03-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0064_auto_20220329_1707'),
        ('geoplaces', '0010_auto_20220329_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RussianRegion',
        ),
    ]
