# Generated by Django 3.2.7 on 2022-04-02 13:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0013_vkcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_idx'),
        ),
    ]
