# Generated by Django 3.2.7 on 2022-04-02 15:21

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0014_auto_20220402_1630'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='search_vector_idx',
        ),
        migrations.AlterField(
            model_name='city',
            name='search_vector',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='search_vector_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
