# Generated by Django 3.2.7 on 2022-04-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0015_auto_20220402_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='foreign_id',
        ),
        migrations.AddField(
            model_name='country',
            name='counry_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Краткое название'),
        ),
    ]
