# Generated by Django 3.2.7 on 2022-04-07 21:14

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0020_auto_20220407_2114'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='search_vector_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='search_vector_en_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
