# Generated by Django 3.2.7 on 2022-04-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0021_auto_20220407_2114'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='search_vector_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='search_vector_en_idx',
        ),
    ]
