# Generated by Django 3.2.7 on 2022-04-07 21:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0023_auto_20220407_2123'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='search_vector_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='search_vector_en_idx',
        ),
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_ru'], name='search_vector_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
