# Generated by Django 3.2.7 on 2022-05-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0024_auto_20220407_2127'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='search_vector_idx',
        ),
        migrations.RemoveField(
            model_name='city',
            name='search_vector',
        ),
    ]
