# Generated by Django 3.2.7 on 2022-07-07 16:29

from django.db import migrations, models
import django.db.models.deletion
import geoplaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0027_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryregion',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vkcity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vkcity',
            name='country_region',
        ),
        migrations.RemoveField(
            model_name='vkcityen',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vkcityen',
            name='country_region',
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Тур направление', 'verbose_name_plural': 'Тур направления'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country_region',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country_region',
        ),
        migrations.AddField(
            model_name='city',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geoplaces.destination', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='destination',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt текст'),
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=geoplaces.models.geo_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='geoplaces.region', verbose_name='Регион Мира'),
        ),
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='map_icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=geoplaces.models.geo_path, verbose_name='Изображение карты'),
        ),
    ]
