# Generated by Django 3.2.7 on 2022-07-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0028_auto_20220707_2016'),
        ('tours', '0085_auto_20220707_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryRegion',
        ),
        migrations.DeleteModel(
            name='VKCity',
        ),
        migrations.DeleteModel(
            name='VKCityEn',
        ),
    ]
