# Generated by Django 3.2.7 on 2022-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplaces', '0029_auto_20220707_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='view',
        ),
        migrations.AddField(
            model_name='destination',
            name='views_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Просмотры'),
        ),
    ]
