# Generated by Django 3.2.7 on 2021-12-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0026_auto_20211223_1538'),
        ('accounts', '0016_remove_user_tmb_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255, verbose_name='Название тура')),
                ('tour_start_date', models.DateField(verbose_name='Дата начала')),
                ('tour_finish_date', models.DateField(verbose_name='Дата завершения')),
                ('tour_price', models.PositiveIntegerField(verbose_name='Цена')),
                ('members_number', models.PositiveIntegerField(verbose_name='Количево участников')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость тура')),
                ('status', models.CharField(max_length=15, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers_orders', to='accounts.customer', verbose_name='Путешествиник')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts_orders', to='accounts.expert', verbose_name='Эксперт')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours_orders', to='tours.touradvanced', verbose_name='Тур')),
            ],
        ),
    ]
