# Generated by Django 3.2.7 on 2022-06-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_expert_preferred_payment_method'),
        ('orders', '0003_auto_20220613_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firsttraveler',
            options={'ordering': ['id'], 'verbose_name': 'Главный Путешественник', 'verbose_name_plural': 'Главные Путешественники'},
        ),
        migrations.AlterModelOptions(
            name='traveler',
            options={'ordering': ['id'], 'verbose_name': 'Путешественник', 'verbose_name_plural': 'Путешественники'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.BigIntegerField(verbose_name='ID Тура')),
                ('tour_name', models.CharField(max_length=255, verbose_name='Название тура')),
                ('tour_start_date', models.DateField(verbose_name='Дата начала')),
                ('tour_finish_date', models.DateField(verbose_name='Дата завершения')),
                ('tour_price', models.PositiveIntegerField(verbose_name='Цена за место')),
                ('travelers_number', models.PositiveIntegerField(verbose_name='Количево участников')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость тура')),
                ('postpay_final_date', models.DateField(verbose_name='Дата постоплаты')),
                ('status', models.CharField(choices=[('pending_confirmation', 'Ожидает подтверждения'), ('pending_prepayment', 'Ожидает_предоплаты'), ('prepayment_overdue', 'Предоплата просрочена'), ('prepayment', 'Предоплата внесена'), ('fullpayment', 'Оплачено полностью')], default='pending_confirmation', max_length=25, verbose_name='Статус')),
                ('difficulty_level', models.PositiveIntegerField(verbose_name='Уровень сложности')),
                ('comfort_level', models.PositiveIntegerField(verbose_name='Уровень комфорта')),
                ('tour_excluded_services', models.JSONField(verbose_name='Не включенные услуги')),
                ('tour_included_services', models.JSONField(verbose_name='Включенные услуги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers_orders', to='accounts.customer', verbose_name='Путешествиник')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts_orders', to='accounts.expert', verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='traveler',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='travelers', to='orders.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
