# Generated by Django 3.2.7 on 2022-06-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_expert_preferred_payment_method'),
        ('orders', '0004_auto_20220613_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers_orders', to='accounts.customer', verbose_name='Покупатель'),
        ),
    ]
