# Generated by Django 3.2.7 on 2022-06-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность тура в днях'),
        ),
        migrations.AddField(
            model_name='order',
            name='postpay',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер постоплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='tour_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Полная стоимость тура'),
        ),
    ]
