# Generated by Django 3.2.7 on 2022-06-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220613_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Полная стоимость бронирования тура'),
        ),
        migrations.AddField(
            model_name='order',
            name='book_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость бронирования за место'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_postpay',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Полный размер постоплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comfort_level',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Уровень комфорта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='difficulty_level',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postpay',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер постоплаты за место'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Не оформлен'), ('cancelled_order', 'Отменен'), ('pending_confirmation', 'Ожидает подтверждения'), ('pending_prepayment', 'Ожидает_предоплаты'), ('prepayment_overdue', 'Предоплата просрочена'), ('prepayment', 'Предоплата внесена'), ('fullpayment', 'Оплачено полностью')], default='new', max_length=25, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tour_excluded_services',
            field=models.JSONField(blank=True, null=True, verbose_name='Не включенные услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tour_included_services',
            field=models.JSONField(blank=True, null=True, verbose_name='Включенные услуги'),
        ),
    ]
