# Generated by Django 3.2.7 on 2022-06-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220614_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tour_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tour_finish_date',
            new_name='finish_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tour_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tour_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tour_start_date',
            new_name='start_date',
        ),
    ]
