# Generated by Django 3.2.7 on 2022-06-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0081_declinereason_staff'),
        ('orders', '0010_auto_20220614_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours_orders', to='tours.tour', verbose_name='Тур'),
        ),
    ]
