# Generated by Django 3.2.7 on 2022-06-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_tour_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tour_id',
            new_name='tour',
        ),
    ]
