# Generated by Django 3.2.7 on 2022-06-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220614_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='index_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
