# Generated by Django 3.2.7 on 2022-06-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20220614_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
