# Generated by Django 3.2.7 on 2022-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20220614_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Не оформлен'), ('cancelled_order', 'Отменен'), ('form_completed', 'Форма заполнена'), ('pending_confirmation', 'Ожидает подтверждения'), ('pending_prepayment', 'Ожидает_предоплаты'), ('prepayment_overdue', 'Предоплата просрочена'), ('prepayment', 'Предоплата внесена'), ('fullpayment', 'Оплачено полностью')], default='new', max_length=25, verbose_name='Статус'),
        ),
    ]
